apiVersion: v1
kind: Service
metadata:
  name: skhappycampus-backend-service
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    run: skhappycampus-backend
  type: NodePort
